# Contents

This is a notebook that imports the robots libraries and a bunch of useful stuff

I use this to perform explorative sessions when debugging/testing some aspects of the library

Feel free to reuse this at the exam!

(remember to use the pdm provided .venv on the top right corner of the notebook)

In [5]:
import pyrobots.rotations as rot
import numpy as np
from rich import print


In [6]:
theta, ax = rot.inverse_rot_mat(
    np.array(
        [
            [0, 0.5, -(np.sqrt(3)/2)],
            [1, 0, 0],
            [0, -(np.sqrt(3)/2), -0.5]
        ]
    )
)

In [7]:
print(theta, ax)

2.4188584057763776 [-0.65465367 -0.65465367  0.37796447]

In [8]:
rot.inverse_rpy(
        np.array(
        [
            [0, 0.5, -(np.sqrt(3)/2)],
            [1, 0, 0],
            [0, -(np.sqrt(3)/2), -0.5]
        ]
    )
)

(-2.0943951023931957, -3.141592653589793, 1.5707963267948966, None)

In [9]:
rot.direct_rot_mat(-np.pi/2, np.array([1,0,0]))

array([[ 1.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  6.123234e-17,  1.000000e+00],
       [ 0.000000e+00, -1.000000e+00,  6.123234e-17]])

In [10]:
Re = np.array([
            [0, 0.5, -(np.sqrt(3)/2)],
            [1, 0, 0],
            [0, -(np.sqrt(3)/2), -0.5]
        ])

Rt = np.array([
            [1, 0, 0],
            [0, 0, 1],
            [0, -1, 0]
        ])

In [11]:
rot.inverse_rpy(Re @ Rt)

(2.6179938779914944, -3.141592653589793, 1.5707963267948966, None)

In [12]:
2.6179938779914944 / np.pi

0.8333333333333334

In [28]:
Z = rot.direct_rot_mat(-np.pi/2, np.array([0,0,1]))
Y = rot.direct_rot_mat(-np.pi/4, np.array([0,1,0]))
X = rot.direct_rot_mat(np.pi/4, np.array([1,0,0]))

In [29]:
R = X @ Y @ Z

In [40]:
R

array([[ 4.32978028e-17,  7.07106781e-01, -7.07106781e-01],
       [-7.07106781e-01, -5.00000000e-01, -5.00000000e-01],
       [-7.07106781e-01,  5.00000000e-01,  5.00000000e-01]])

In [37]:
val, vec = np.linalg.eig(R)

In [38]:
val

array([-0.5+0.8660254j, -0.5-0.8660254j,  1. +0.j       ])

In [39]:
vec

array([[-7.51095729e-17-0.57735027j, -7.51095729e-17+0.57735027j,
        -5.77350269e-01+0.j        ],
       [ 7.07106781e-01+0.j        ,  7.07106781e-01-0.j        ,
        -1.31045324e-16+0.j        ],
       [-6.26003425e-17-0.40824829j, -6.26003425e-17+0.40824829j,
         8.16496581e-01+0.j        ]])