# Contents

This is a notebook that imports the robots libraries and a bunch of useful stuff

I use this to perform explorative sessions when debugging/testing some aspects of the library

Feel free to reuse this at the exam!

(remember to use the pdm provided .venv on the top right corner of the notebook)

In [1]:
import pyrobots as pr
import robots as rb
import numpy as np
from rich import print


## BASIC ROTATION MATRICES AND TRANSFORMATIONS

In [4]:
#Find the transformation matrix between two frames
O_R_i=np.array([[0,0,1],[0,-1,0],[1,0,0]])
O_R_f=np.array([[0,1,0],[0,0,1],[1,0,0]])
i_R_f=O_R_i.T@O_R_f
print(i_R_f)

#create the basic matrices around x,y,z
theta='pi/2'
Rx_theta=rb.rotation_direct(theta, axis='x')
Ry_theta=rb.rotation_direct(theta, axis='y')
Rz_theta=rb.rotation_direct(theta, axis='z')

[[ 1  0  0]
 [ 0  0 -1]
 [ 0  1  0]]

🔄 Direct Rotation Matrix:
[[ 1.,  0.,  0.],
 [ 0.,  0., -1.],
 [ 0.,  1.,  0.]]

🔄 Direct Rotation Matrix:
[[ 0.,  0.,  1.],
 [ 0.,  1.,  0.],
 [-1.,  0.,  0.]]

🔄 Direct Rotation Matrix:
[[ 0., -1.,  0.],
 [ 1.,  0.,  0.],
 [ 0.,  0.,  1.]]

## DIRECT ROTATION

In [24]:
#find the rotation matrix given the axis and angle
theta='pi/2'
R=rb.rotation_direct(theta, '1,0,0')

🔄 Direct Rotation Matrix:
[[ 1.,  0.,  0.],
 [ 0.,  0., -1.],
 [ 0.,  1.,  0.]]

## INVERSE ROTATION 

In [26]:
#find the angle and axis given the rotation matrix
R="[[0,sqrt(3)/2,1/2],[0,1/2,-sqrt(3)/2],[-1,0,0]]"
rb.rotation_inverse(R, fract=True)

Inverse Rotation:
        📐 theta(s) = [582712/319561, -582712/319561]
        📏 axis = [[1/√5, 726141/937444, -1/√5],
 [-1/√5, -726141/937444, 1/√5]]

## DIRECT EULER

In [ ]:
alpha_1="pi/4" #angle around y
alpha_2="-pi/4" #angle around x
alpha_3="2*pi/3" #angle around y

Ry_1=rb.rotation_direct(alpha_1, axis='y')
Rx_2=rb.rotation_direct(alpha_2, axis='x')
Ry_3=rb.rotation_direct(alpha_3, axis='y')

R=Ry_1@Rx_2@Ry_3

## INVERSE EULER 
there's no code for the inverse euler problem :(

## EXAMPLE EXAM

In [27]:
#EXERCISE 1
alpha_1="pi/4"
alpha_2="-pi/4"
alpha_3="2*pi/3"

Ry_1=rb.rotation_direct(alpha_1, axis='y')
Rx_2=rb.rotation_direct(alpha_2, axis='x')
Ry_3=rb.rotation_direct(alpha_3, axis='y')

ORf=Ry_1@Rx_2@Ry_3
fmt_foo = lambda arr: rb.fmt_array(ORf, False, False)
print(fmt_foo(ORf))

ORi=np.array([[0,np.sqrt(3)/2,1/2],[0,1/2,-np.sqrt(3)/2],[-1,0,0]])

print('orf:',ORf)
print('transpose:',ORi.T)

iRf=np.matmul(ORi.T,ORf)
fmt_foo = lambda arr: rb.fmt_array(iRf, False, True)
print(fmt_foo(iRf))

🔄 Direct Rotation Matrix:
[[ 0.70710678,  0.        ,  0.70710678],
 [ 0.        ,  1.        ,  0.        ],
 [-0.70710678,  0.        ,  0.70710678]]

🔄 Direct Rotation Matrix:
[[ 1.        ,  0.        ,  0.        ],
 [ 0.        ,  0.70710678,  0.70710678],
 [ 0.        , -0.70710678,  0.70710678]]

🔄 Direct Rotation Matrix:
[[-0.5      ,  0.       ,  0.8660254],
 [ 0.       ,  1.       ,  0.       ],
 [-0.8660254,  0.       , -0.5      ]]

[[-0.78656609, -0.5       ,  0.36237244],
 [-0.61237244,  0.70710678, -0.35355339],
 [-0.07945931, -0.5       , -0.86237244]]

orf: [[-0.78656609 -0.5         0.36237244]
 [-0.61237244  0.70710678 -0.35355339]
 [-0.07945931 -0.5        -0.86237244]]

transpose: [[ 0.         0.        -1.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.5       -0.8660254  0.       ]]

[[0.0795, 0.5000, 0.8624],
 [-0.9874, -0.0795, 0.1370],
 [0.1370, -0.8624, 0.4874]]